# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='location',
        ),
    ]
