# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20180718_1758'),
        ('restaurants', '0012_auto_20180717_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='owner',
        ),
        migrations.DeleteModel(
            name='RestaurantLocation',
        ),
    ]
